# Generated by Django 4.1.2 on 2023-11-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customadmin', '0002_delete_maaa'),
    ]

    operations = [
        migrations.CreateModel(
            name='demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dem', models.CharField(max_length=10)),
            ],
        ),
    ]
