# Generated by Django 4.1.2 on 2023-11-13 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='demo',
        ),
    ]
