# Generated by Django 4.1.2 on 2023-11-06 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_templates_find'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templates',
            name='find',
        ),
    ]
