# Generated by Django 4.1.2 on 2023-11-06 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_templates_find'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Templates',
        ),
    ]
