# Generated by Django 4.1.2 on 2023-11-06 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_templates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Templates',
        ),
        migrations.DeleteModel(
            name='TemplatesType',
        ),
    ]
