# Generated by Django 4.1.2 on 2023-11-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='category',
            field=models.TextField(blank=True),
        ),
    ]
