# Generated by Django 4.1.2 on 2023-11-06 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_templates_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templates',
            old_name='type',
            new_name='types',
        ),
    ]
