# Generated by Django 4.1.2 on 2023-11-06 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_rename_type_templates_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templates',
            old_name='types',
            new_name='temp_type',
        ),
    ]
