# Generated by Django 4.1.2 on 2023-11-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_remove_templates_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatestype',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
