# Generated by Django 4.1.2 on 2023-11-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_templatestype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupen_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, unique=True)),
                ('coupen_percentage', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('coupen_used', models.IntegerField(default=0)),
                ('used_user', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
