# Generated by Django 4.1.2 on 2023-11-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentFailed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=250)),
                ('reason', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=250)),
                ('source', models.CharField(max_length=250)),
                ('step', models.CharField(max_length=250)),
                ('payment_id', models.CharField(max_length=250)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
