# Generated by Django 4.1.2 on 2023-11-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
