# Generated by Django 4.1.2 on 2023-11-30 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_orders_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='expiry_date',
        ),
    ]
