# Generated by Django 4.1.2 on 2024-01-03 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginregister', '0010_profile_is_verified'),
        ('mainapp', '0022_paymentsuccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateTimeField()),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('reminder_date', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.orders')),
                ('payment_success', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.paymentsuccess')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginregister.profile')),
            ],
        ),
    ]
