# Generated by Django 4.1.2 on 2024-01-03 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_renewal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Renewal',
        ),
    ]
