# Generated by Django 4.1.2 on 2024-01-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_paymentsc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentSC',
        ),
    ]
