# Generated by Django 4.1.2 on 2024-02-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_renewal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Akash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
    ]
