# Generated by Django 4.1.2 on 2024-02-16 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_akash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Akash',
        ),
    ]
