# Generated by Django 4.1.2 on 2024-02-28 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_delete_akash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupen_code',
            name='coupen_used',
        ),
        migrations.RemoveField(
            model_name='coupen_code',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='coupen_code',
            name='used_user',
        ),
    ]
