# Generated by Django 4.1.2 on 2024-02-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_remove_coupen_code_coupen_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupen_code',
            name='coupen_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coupen_code',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coupen_code',
            name='used_user',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
