# Generated by Django 4.1.2 on 2024-02-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_coupen_code_coupen_used_coupen_code_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='template_img',
            field=models.ImageField(default='exit', upload_to='orderimage'),
            preserve_default=False,
        ),
    ]
