# Generated by Django 4.1.2 on 2024-02-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_orders_template_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsuccess',
            name='coupen_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymentsuccess',
            name='email',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentsuccess',
            name='final_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentsuccess',
            name='host_name',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentsuccess',
            name='plan',
            field=models.CharField(blank=True, default=True, max_length=20),
        ),
        migrations.AddField(
            model_name='paymentsuccess',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentsuccess',
            name='razorpay_payment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentsuccess',
            name='template_amount',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentsuccess',
            name='template_category',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentsuccess',
            name='template_img',
            field=models.ImageField(default='exit', upload_to='orderimage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentsuccess',
            name='template_name',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentsuccess',
            name='username',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
