# Generated by Django 4.2.10 on 2024-03-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_remove_paymentsuccess_coupen_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='template_id',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
    ]
