# Generated by Django 4.2.10 on 2024-03-21 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_orders_template_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templates',
            name='find',
        ),
    ]
