# Generated by Django 4.2.10 on 2024-03-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_remove_templates_find'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='find',
            field=models.CharField(default='exit', max_length=40),
            preserve_default=False,
        ),
    ]
