# Generated by Django 4.1.2 on 2023-11-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginregister', '0003_storedotps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storedotps',
            old_name='is_active',
            new_name='otp_active',
        ),
    ]
