# Generated by Django 4.1.2 on 2023-11-14 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginregister', '0005_emailverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
