# Generated by Django 4.1.2 on 2024-02-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginregister', '0010_profile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cuid',
            field=models.TextField(default='yes'),
            preserve_default=False,
        ),
    ]
