# Generated by Django 4.1.2 on 2024-02-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginregister', '0011_profile_cuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cuid',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
