# Generated by Django 4.1.2 on 2024-02-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginregister', '0012_alter_profile_cuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='delete_token',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
    ]
