# Generated by Django 4.1.2 on 2024-02-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginregister', '0014_deletetoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeleteToken',
        ),
    ]
